services:
  my_service:
    image: alpine
    command: sh -c "apk add --no-cache curl && sleep infinity"
    tty: true
    stdin_open: true
    restart: always


networks:
  mynet1:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254