version: "3.7"

services:
  fluent-bit:
    tty: true
    image: grafana/fluent-bit-plugin-loki:main-e2ed1c0
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://write:3100/loki/api/v1/push
      - SERVER_ID=12345
    volumes:
      - ./configs/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - public
networks:
  public:
    name: public