services:
  my_service:
    image: alpine
    command: sh -c "apk add --no-cache curl && sleep infinity"
    tty: true
    stdin_open: true
    restart: always
    networks:
      - network


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1